// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Para PostgreSQL, DATABASE_URL debe estar en el archivo .env
// Formato: postgresql://usuario:contraseña@localhost:5432/nombre_base_datos?schema=public
const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL no está definida en el archivo .env. " +
    "Por favor, crea un archivo .env con: DATABASE_URL=postgresql://usuario:contraseña@localhost:5432/pm_database?schema=public"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
